# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20161130_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirtURL', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shirtURL',
        ),
    ]
