# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20161206_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestedshirts',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shirtholdings',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='teamProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirtCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirtImg',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wanted',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='interestedShirts',
        ),
        migrations.DeleteModel(
            name='ShirtHoldings',
        ),
    ]
