# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_auto_20161215_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('order', models.IntegerField()),
                ('sentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageFrom', to=settings.AUTH_USER_MODEL, unique=True)),
                ('sentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageTo', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
